export enum UpdateType {
  'BASE_DETAILS' = 'BASE_DETAILS',
  'EQUIPMENT' = 'EQUIPMENT',
  'FEATURES' = 'FEATURES',
  'LANGUAGES' = 'LANGUAGES',
  'PROFICIENCIES' = 'PROFICIENCIES',
  'SPELLS' = 'SPELLS',
  'SPELL_SLOTS' = 'SPELL_SLOTS',
  'WEAPONS' = 'WEAPONS'
}