export enum UpdateType {
  'ABILITY_SCORES' = 'ABILITY_SCORES',
  'BASE_DETAILS' = 'BASE_DETAILS',
  'EQUIPMENT' = 'EQUIPMENT',
  'FEATURES' = 'FEATURES',
  'LANGUAGES' = 'LANGUAGES',
  'NOTES' = 'NOTES',
  'PROFICIENCIES' = 'PROFICIENCIES',
  'SPELLS' = 'SPELLS',
  'SPELL_SLOTS' = 'SPELL_SLOTS',
  'WEAPONS' = 'WEAPONS'
}