name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/firebase-hosting-merge.yml

  create_release:
    uses: ./.github/workflows/create-release.yml
    needs: deploy
    
