name: Create Release

on:
  workflow_call

jobs:
  get_package_version:
    name: Get Package Version
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ steps.package-version.outputs.current-version }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - run: echo "Reading package.json..."
    - name: Get package version
      id: package-version
      run: echo "current-version=$(cat ./package.json | jq '.version' | tr -d '"')" >> $GITHUB_OUTPUT
    - name: Exit if no version found
      run: |
        if [[ ${{ steps.package-version.outputs.current-version }} == 'null' ]];
        then echo "Failed to retrieve package version in get_package_version job :("
        exit 1;
        fi
    - run: echo "Version ${{ steps.package-version.outputs.current-version }}"

  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs:
      - get_package_version
    outputs:
      html_url: ${{ steps.create-release.outputs.html_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - run: echo "Creating release for package version ${{ needs.get_package_version.outputs.current-version }}..."
      - name: Create release action
        id: create-release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: false
          draft: false
          generateReleaseNotes: true
          makeLatest: true
          omitBody: false
          prerelease: false
          skipIfReleaseExists: true
          tag: 'v${{ needs.get_package_version.outputs.current-version }}'
          updateOnlyUnreleased: true
      - name: Release url
        run: |
          if [ "${{ steps.create-release.outputs.html_url }}" != '' ];
          then echo ${{ steps.create-release.outputs.html_url }};
          fi
